### PR TITLE
Lesson description

### PR DESCRIPTION
**Pull request by jashi202jg**

### CODE REVIEW

**Comment by JithinKS97** [comment]
Resolved #5

**Comment by JithinKS97** [comment]
@nickmcintyre, please take a look

**Comment by nickmcintyre** [comment]
This works great! I also like the polishing that's gone in to the UI. A couple of minor issues:

- I viewed the description of a dummy lesson and noticed activities were listed twice. I believe the cause is here:

```
<List.Item>
    <List.Header>inClassActivites</List.Header>
    {this.state.description.inClassActivities}
</List.Item>
<List.Item>
    <List.Header>In Class Activites</List.Header>
    {this.state.description.inClassActivities}
</List.Item>
```

- I suggest staying consistent with the label "In-Class Activities" between the editor and viewer

**Comment by JithinKS97** [comment]
I removed the dulplicaton. Also is it necessary that we make every field required?

**Pull request merged**
